// Kamile Kacinskaite
// Arcade Ticketing System Project
// C00312390
// Date submitted: 21/04/2026

package dao;

import db.DBConnection;
import model.Customer;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for the Customer table.
 * Handles all database operations related to customers — create, read, update, and delete.
 */

public class CustomerDAO {

    /**
     * Inserts a new customer into the database.
     * The customer_id is auto-generated by the database, so it is not included here.
     *
     * @param c The Customer object containing the details to insert.
     */
    public void addCustomer(Customer c) {
        String sql = "INSERT INTO customer (name, email, tickets) VALUES (?, ?, ?)";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, c.getName());
            ps.setString(2, c.getEmail());
            ps.setInt(3, c.getTickets());
            ps.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Retrieves all customers from the database.
     *
     * @return A list of all Customer objects, or an empty list if none exist.
     */
    public List<Customer> getAllCustomers() {
        List<Customer> customers = new ArrayList<>();
        String sql = "SELECT * FROM customer";

        try (Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {


            // Loop through each row in the result and map it to a Customer object
            while (rs.next()) {
                Customer c = new Customer();
                c.setCustomerId(rs.getInt("customer_id"));
                c.setName(rs.getString("name"));
                c.setEmail(rs.getString("email"));
                c.setTickets(rs.getInt("tickets"));
                customers.add(c);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return customers;
    }

    /**
     * Retrieves a single customer by their ID.
     * Used by staff when topping up a customer's ticket balance.
     *
     * @param id The customer_id to search for.
     * @return The matching Customer object, or null if not found.
     */
    public Customer getCustomerById(int id) {
        String sql = "SELECT * FROM customer WHERE customer_id = ?";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Customer c = new Customer();
                c.setCustomerId(rs.getInt("customer_id"));
                c.setName(rs.getString("name"));
                c.setEmail(rs.getString("email"));
                c.setTickets(rs.getInt("tickets"));
                return c;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;    // No customer found with that ID
    }

    /**
     * Retrieves a single customer by their email address.
     * Used during customer login to look up their account.
     *
     * @param email The email address to search for.
     * @return The matching Customer object, or null if not found.
     */
    public Customer getCustomerByEmail(String email) {
        String sql = "SELECT * FROM customer WHERE email = ?";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, email);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Customer c = new Customer();
                c.setCustomerId(rs.getInt("customer_id"));
                c.setName(rs.getString("name"));
                c.setEmail(rs.getString("email"));
                c.setTickets(rs.getInt("tickets"));
                return c;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;    // No customer found with that email
    }

    /**
     * Updates an existing customer's details in the database.
     * Matches the record using customer_id.
     *
     * @param c The Customer object with updated values.
     */
    public void updateCustomer(Customer c) {
        String sql = "UPDATE customer SET name=?, email=?, tickets=? WHERE customer_id=?";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, c.getName());
            ps.setString(2, c.getEmail());
            ps.setInt(3, c.getTickets());
            ps.setInt(4, c.getCustomerId());
            ps.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Deletes a customer from the database by their ID.
     *
     * @param id The customer_id of the customer to remove.
     */
    public void deleteCustomer(int id) {
        String sql = "DELETE FROM customer WHERE customer_id=?";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, id);
            ps.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}