// Kamile Kacinskaite
// Arcade Ticketing System Project
// C00312390
// Date submitted: 21/04/2026

package dao;

import db.DBConnection;
import model.Game;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for the Game table.
 * Handles all database operations related to arcade games — create, read, update, and delete.
 */
public class GameDAO {

    /**
     * Inserts a new game into the database.
     * The game_id is auto-generated by the database.
     *
     * @param g The Game object containing the details to insert.
     */
    public void addGame(Game g) {
        String sql = "INSERT INTO game (game_name, cost_per_play, tickets_rewarded) VALUES (?, ?, ?)";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, g.getGameName());
            ps.setInt(2, g.getCostPerPlay());
            ps.setInt(3, g.getTicketsRewarded());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * Retrieves all games from the database.
     *
     * @return A list of all Game objects, or an empty list if none exist.
     */
    public List<Game> getAllGames() {
        List<Game> games = new ArrayList<>();
        String sql = "SELECT * FROM game";
        try (Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            // Map each row in the result to a Game object using the full constructor
            while (rs.next()) {
                Game g = new Game(
                        rs.getInt("game_id"),
                        rs.getString("game_name"),
                        rs.getInt("cost_per_play"),
                        rs.getInt("tickets_rewarded")
                );
                games.add(g);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return games;
    }

    /**
     * Updates an existing game's details in the database.
     * Matches the record using game_id.
     *
     * @param g The Game object with updated values.
     */
    public void updateGame(Game g) {
        String sql = "UPDATE game SET game_name=?, cost_per_play=?, tickets_rewarded=? WHERE game_id=?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, g.getGameName());
            ps.setInt(2, g.getCostPerPlay());
            ps.setInt(3, g.getTicketsRewarded());
            ps.setInt(4, g.getGameId());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Deletes a game from the database by its ID.
     *
     * @param gameId The game_id of the game to remove.
     */
    public void deleteGame(int gameId) {
        String sql = "DELETE FROM game WHERE game_id=?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, gameId);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}