// Kamile Kacinskaite
// Arcade Ticketing System Project
// C00312390
// Date submitted: 21/04/2026

package dao;

import db.DBConnection;
import model.Prize;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for the Prize table.
 * Handles all database operations related to prizes — create, read, update, and delete.
 */

public class PrizeDAO {

    /**
     * Inserts a new prize into the database.
     * The prize_id is auto-generated by the database.
     *
     * @param p The Prize object containing the details to insert.
     */
    public void addPrize(Prize p) {
        String sql = "INSERT INTO prize (prize_name, ticket_cost, stock) VALUES (?, ?, ?)";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, p.getPrizeName());
            ps.setInt(2, p.getTicketCost());
            ps.setInt(3, p.getStock());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Retrieves all prizes from the database.
     *
     * @return A list of all Prize objects, or an empty list if none exist.
     */
    public List<Prize> getAllPrizes() {
        List<Prize> prizes = new ArrayList<>();
        String sql = "SELECT * FROM prize";
        try (Connection con = DBConnection.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            // Map each row in the result to a Prize object using the full constructor
            while (rs.next()) {
                Prize p = new Prize(
                        rs.getInt("prize_id"),
                        rs.getString("prize_name"),
                        rs.getInt("ticket_cost"),
                        rs.getInt("stock")
                );
                prizes.add(p);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return prizes;
    }

    /**
     * Updates an existing prize's details in the database.
     * Matches the record using prize_id.
     *
     * @param p The Prize object with updated values.
     */
    public void updatePrize(Prize p) {
        String sql = "UPDATE prize SET prize_name=?, ticket_cost=?, stock=? WHERE prize_id=?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, p.getPrizeName());
            ps.setInt(2, p.getTicketCost());
            ps.setInt(3, p.getStock());
            ps.setInt(4, p.getPrizeId());
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Deletes a prize from the database by its ID.
     *
     * @param prizeId The prize_id of the prize to remove.
     */
    public void deletePrize(int prizeId) {
        String sql = "DELETE FROM prize WHERE prize_id=?";
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, prizeId);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}